name: Run all tests
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - uses: android-actions/setup-android@v2
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sdkmanager "platforms;android-33"

    - name: Execute Gradle allTests
      run: ./gradlew allTests  --scan

