name: Run semantic-release on dry-run mode
permissions:
  actions: write
  contents: write
on:
  workflow_call:
    outputs:
      release_triggered:
        value: ${{ jobs.semantic-dry-run.outputs.new_release_published }}
      new_major_version:
        value: ${{ jobs.semantic-dry-run.outputs.new_major_version }}
      new_minor_version:
        value: ${{ jobs.semantic-dry-run.outputs.new_minor_version }}
      new_patch_version:
        value: ${{ jobs.semantic-dry-run.outputs.new_patch_version }}
      new_combined_version:
        value: ${{ jobs.semantic-dry-run.outputs.new_combined_version }}
jobs:
  semantic-dry-run:
    runs-on: ubutu-latest
    outputs:
      release_triggered: ${{ steps.semantic.outputs.new_release_published }}
      new_major_version: ${{ steps.semantic.outputs.new_release_major_version }}
      new_minor_version: ${{ steps.semantic.outputs.new_release_minor_version }}
      new_patch_version: ${{ steps.semantic.outputs.new_release_patch_version }}
      new_combined_version: ${{ steps.bash-script.outputs.new_combined_version }}
    steps:
      - uses: actions/checkout@v4
      - name: Semantic Release Dry Run
        uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: true
        id: semantic
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Save combined version to output
        id: bash-script
        run: |
          echo new_combined_version=\
          ${{ jobs.semantic.outputs.new_major_version }}.\
          ${{ jobs.semantic.outputs.new_minor_version }}.\
          ${{ jobs.semantic.outputs.new_patch_version }}" >> "$GITHUB_OUTPUT"
        shell: bash