name: Check semantic release outputs on dry run`
permissions:
  actions: write
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Semantic Release Dry Run
        uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: true
        id: semantic-dry
      - name: Print outputs
        run: |
          echo "new_release_published = ${{ steps.semantic-dry.output.new_release_published }}"
          echo "new_release_version = ${{ steps.semantic-dry.output.new_release_version }}"
          echo "new_release_major_version = ${{ steps.semantic-dry.output.new_release_major_version }}"
          echo "new_release_minor_version = ${{ steps.semantic-dry.output.new_release_minor_version }}"
          echo "new_release_patch_version = ${{ steps.semantic-dry.output.new_release_patch_version }}"
          echo "new_release_channel = ${{ steps.semantic-dry.output.new_release_channel }}"
          echo "new_release_notes = ${{ steps.semantic-dry.output.new_release_notes }}"
          echo "new_release_git_head = ${{ steps.semantic-dry.output.new_release_git_head }}"
          echo "new_release_git_tag = ${{ steps.semantic-dry.output.new_release_git_tag }}"
          echo "last_release_version = ${{ steps.semantic-dry.output.last_release_version }}"
          echo "last_release_git_head = ${{ steps.semantic-dry.output.last_release_git_head }}"
          echo "last_release_git_tag = ${{ steps.semantic-dry.output.last_release_git_tag }}"
        shell: bash