name: CI Test Build

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - uses: android-actions/setup-android@v2
    - run: sdkmanager "platforms;android-33"

    - name: Execute Gradle build
      run: ./gradlew build