name: Test Secret
on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle help
        run: ./gradlew help
        env:
          THIS_SHOULD_BE_REDACTED: ${{ secrets.THIS_SHOULD_BE_REDACTED }}